config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  devise_for :users
  root 'home#index'
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list

  def completed?
    !completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  validates_presence_of :user_id
  has_many :todo_items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :todo_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render :index
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, except: [:create]
  before_action :authenticate_user!

  def create 
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    redirect_to @todo_list
  end

  def destroy
    if @todo_item.destroy
      flash[:success] = "Todo List item was deleted."
    else
      flash[:error] = "Todo List item was not deleted."
    end
    redirect_to @todo_list
  end

  def complete
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to @todo_list, notice: "Todo item completed"
  end


  private

  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def set_todo_item
    @todo_item = @todo_list.todo_items.find(params[:id])
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    if current_user
      @todo_lists = current_user.todo_lists
    else
      @todo_lists = TodoList.all
    end
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = current_user.todo_lists.create(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_todo_list
    @todo_list = TodoList.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def todo_list_params
    params.require(:todo_list).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @todo_items = TodoItem.todo_list_id.where(:user_id => current_user)
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/home/index.html.erb
<div class="home">
  <!-- <h1>TOOODOOOO!!</h1> -->
</div>  


<br>
<br>
<div class="image">
  <%= image_tag("list.png") %>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <%= link_to "Spot Or Not", root_path, id: "logo" %>
      </div>
      <div class="col-md-6">
        <%= form_tag("/song_suggestions/show", method: "get", class: "search-form") do %>
          <%= text_field_tag(:q, params[:q], class: "search-field", placeholder: "Search for songs") %>
          <%= submit_tag("Search", class: "search-button btn btn-primary btn-sm") %>
        <% end %>
      </div>
      <nav class="col-md-3">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", '#' %></li>
                <li><%= link_to "Settings", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", destroy_user_session_path,
                                         method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Log in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoMvc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>

<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div>
        <%= link_to "Todo Lists", root_path, id: "logo" %>
      </div>
        
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=""><a href="/users/sign_in">Sign In <span class="sr-only">(current)</span></a></li>
        <li><a href="/users/sign_up">Sign Up</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          <% if current_user %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %> 
          <% if current_user %> 
            <li><%= link_to "Your Lists", todo_lists_path %></li>
          <% else %>
          <% end %>
            <!-- <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li> -->
          </ul>
        <!-- </li> -->
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="This Doesn't Do Anything">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
 -->      <!-- <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
      </ul> -->
    </div>
  </div>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>



<%= yield %>
  </div>
</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
  <%= f.text_field :content, placeholder: "New Todo" %>
  <%= f.submit %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="edit-item">
  <div class="row clearfix">
    <% if todo_item.completed? %>
      <div class="complete">
        <%= link_to "Mark as Complete", complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch %>
      </div>
      <div class="=todo_item">
        <p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
      </div>
      <div class="trash">
        <%= link_to "Delete", todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    <% else %>
      <div class="complete">
        <%= link_to "Mark as Complete", complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch %>
          <i class="fa fa-check"></i>
      </div>
      <div class="=todo_item">
        <p><%= todo_item.content %></p>
      </div>
      <div class="trash">
        <%= link_to "Delete", todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } %>
          <i class="fa fa-trash"></i>
      </p>
      </div>
    <% end %>
  </div>
</div>

app/views/todo_items/index.html.erb
  <h1>Listing Todo Lists</h1>
  <div class="table">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>
  </div>  
    <tbody>
      <% @todo_items do |todo_list| %>
        <tr>
          <td><%= todo_list.title %></td>
          <td><%= todo_list.description %></td>
          <td><%= link_to 'Show', todo_list %></td>
          <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
          <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="edit-view">
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>  
<% end %>

app/views/todo_lists/_todolist.html.erb
<tr>
  <td><%= todo_list.title %></td>
  <td><%= todo_list.description %></td>
  <td><%= link_to 'Show', todo_list %></td>
  <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
  <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/todo_lists/create.js.erb
//$('.jaquerry').append("<%= escape_javascript(render(partial: 'todo_lists/todolist', locals: {todo_list: @todo_list})) %>");
// $('.jaquerry_body').val('')

//$('.jaquerry').append('<%= escape_javascript(render :partial => @todo_list) %>');
//$('.jaquerry_body').val('')

app/views/todo_lists/edit.html.erb
<div class="edit-view-h1">
  <h1>Editing Todo List</h1>
</div>

<%= render 'form' %>

<br>
<div class="edit-links">
  <%= link_to "Lists", todo_lists_path, class: "btn btn-default" %>
</div>

app/views/todo_lists/index.html.erb
<div class="new-list">
  <p id="notice"><%= notice %></p>

  <h1>Listing Todo Lists</h1>
  <div class="table">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>
  </div>  
    <tbody>
      <% @todo_lists.each do |todo_list| %>
        <tr>
          <td><%= todo_list.title %></td>
          <td><%= todo_list.description %></td>
          <td><%= link_to 'Show', todo_list %></td>
          <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
          <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <a href="/todo_lists/new" class="btn btn-default">New Todo List</a>  
</div>

app/views/todo_lists/new.html.erb
<div class="new_list">
  <h1>New Todo List</h1>

  <%= render 'form' %>
<br>
  <div class="new-list-back-button">
    <%= link_to "Lists", todo_lists_path, class: "btn btn-default" %>
  </div>
</div>

app/views/todo_lists/show.html.erb
<div class="show_page">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @todo_list.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @todo_list.description %>
  </p>
</div>
  <div class="todo_items_wrapper">
    <%= render @todo_list.todo_items %>
    <br>
    <div id="form">
      <%= render "todo_items/form" %>
    </div>
  </div>

<br>
<br>
<div class="show_links">
  <%= link_to "Lists", todo_lists_path, class: "btn btn-default" %>
</div>

app/views/users/index.html.erb
<div class="new-list">
  <p id="notice"><%= notice %></p>

  <br>

  <a href="/todo_lists/new" class="btn btn-default">New Todo List</a>  
</div>

app/views/users/show.html.erb
<div class="show_page">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @todo_list.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @todo_list.description %>
  </p>
</div>
  <div class="todo_items_wrapper">
    <%= render @todo_list.todo_items %>
    <br>
    <div id="form">
      <%= render "todo_items/form" %>
    </div>
  </div>

<br>
<br>
<div class="show_links">
  <a href="/todo_lists" class="btn btn-default">Back</a>  
</div>